<?php

/**
 * @file
 * Provides integration with the Howler.js library.
 */

/**
 * Implements hook_library_info_alter().
 */
function howlerjs_library_info_alter(&$libraries, $module) {
  if ($module == 'howlerjs') {
    // In case that the libraries are included locally, use those instead of the
    // CDN.
    // @see https://www.drupal.org/node/3099614
    $library_file_finder = \Drupal::service('library.libraries_directory_file_finder');
    $current_libraries = [
      'howler' => 'howler.min.js',
      'howler.core' => 'howler.core.min.js',
      'howler.spatial' => 'howler.spatial.min.js',
    ];
    foreach ($current_libraries as $current_library_id => $current_library_file) {
      if (isset($libraries[$current_library_id])) {
        $path = $library_file_finder->find("$module/$current_library_file");
        if ($path) {
          $libraries[$current_library_id]['js'] = [
            '/' . $path => ['minified' => TRUE]
          ];
        }
      }
    }
  }
}
