<?php

/**
 * @file
 * Provides integration with the Tiny HTML Audio Player library.
 */

/**
 * Implements hook_library_info_alter().
 */
function tiny_html_audio_player_library_info_alter(&$libraries, $module) {
  if ($module == 'tiny_html_audio_player') {
    // Use local library files rather than CDN if they're present.
    // @see https://www.drupal.org/node/3099614
    $library_file_finder = \Drupal::service('library.libraries_directory_file_finder');
    $current_libraries = [
      'js' => 'tiny_html_audio_player/tinyPlayer.js',
      'css' => 'tiny_html_audio_player/tinyPlayer.css',
      'fa_css' => 'fontawesome/css/all.min.css',
    ];

    $path = $library_file_finder->find($current_libraries['js']);
    if ($path) {
      $libraries['tiny_html_audio_player']['js'] = [
        '/' . $path => ['minified' => FALSE, 'external' => FALSE],
      ];
    }
    $path = $library_file_finder->find($current_libraries['css']);
    if ($path) {
      $libraries['tiny_html_audio_player']['css'] = [
        'theme' => [
          '/' . $path => ['minified' => FALSE, 'external' => FALSE],
        ],
      ];
    }
    $path = $library_file_finder->find($current_libraries['fa_css']);
    if ($path) {
      $libraries['tiny_html_audio_player']['fa_css'] = [
        'theme' => [
          '/' . $path => ['minified' => TRUE, 'external' => FALSE],
        ],
      ];
    }
  }
}

/**
 * Implements hook_theme().
 */
function tiny_html_audio_player_theme() {
  return [
    'tiny_html_audio_player' => [
      'variables' => [
        'title' => NULL,
        'src' => NULL,
        'src_type' => NULL,
        'attributes' => NULL,
      ],
    ],
  ];
}
